### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by shermp** [shermp/UNCaGED#3]
It's becoming clear to me that errors for this library need a bit of an overhaul, but I'm not entirely certain of the best way to handle it.

I think the library needs to distinguish between errors that are specific to UNCaGED (eg: calibre not found, calibre busy, invalid password), and more generic errors (eg: network and file errors).

One possible solution is type assertion. Create an UC specific error type and some error sentinals for UC errors, and just wrap all other errors. The client can check the type, and respond accordingly.

@geek1011 do you have any suggestions on what the best way to approach this?

**Comment by pgaskin** [comment]
I've tried quite a few different error handling patterns (custom structs, type assertion, predefined errors, string-based, etc), and none of them have a clear advantage over the others. I usually tend to use the built-in errors along with some helper functions for smaller programs or commands. For larger ones, it depends on what I'm doing.

It basically comes down to what you are looking for (wrapping, chaining, custom messages, context, etc).

Also, one thing I find makes this easier is splitting functionality (for example, in Kobo-UNCaGED, I'd personally split the Kobo, the UNCaGED, and the command code). This reduces the amount of information which needs to be stored in each error, makes it easier to unit test, and makes it easier to implement new features.

**Comment by shermp** [comment]
I might keep it relatively simple then. Sentinel errors of a custom type for errors that require context, and wrapping for all other errors. The client can use a type switch to decide how to handle things.

Thanks for the feedback.

**Comment by shermp** [comment]
Lately I've been wondering if the interface based approach I took with this was really the best way to do things. (it was developed when the whole interface thing finally clicked with me, and I may have gone overboard...) I guess callbacks could have been another option.

On the one hand, it seems to have made error handling more convoluted than perhaps it needed to be. On the other hand, in theory, the client implementation shouldn't have to know much about the internals of how the calibre wireless connection actually works.

**Comment by shermp** [comment]
#4 provides updated error handling. Closing.
